const fibonacci = () => {
  let fib = [0, 1];

  //starting with an array populated with positions 1 and two.

  for (var i = 2; i < 10; i++) {
    // starting at the 3rd space in the fib array until the 10th

    fib[i] = fib[i - 1] + fib[i - 2];

    // add the previous 2 spaces in the fib array for each iteration
  };

  console.log(fib);
};

fibonacci();

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
